set nocompatible

" file type
filetype on
filetype indent on
filetype plugin on
set encoding=utf-8

" **** UI ****
syntax on
colorscheme gruvbox
set background=dark
set macligatures
set number
set ruler
set colorcolumn=90
set showcmd
set showmode
set cursorline  
let macvim_skip_colorscheme=1
set visualbell

" **** Editor ****
set backspace=indent,eol,start
let mapleader=","
set expandtab
set hlsearch
set incsearch
set laststatus=2
set ttyfast
set hidden
set history=100

set autoread

" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif

" *** SYNTASTIC ***
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0

"let g:syntastic_java_checkers = []

" end syntastic config 

" *** ALE ***
let g:ale_fixers = { 'java':['google_java_format']}  


" *** MAPPINGS ***
" open vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>


" PLUGINS "
" --------
"
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdTree'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
"Plug 'flazz/vim-colorschemes'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'easymotion/vim-easymotion'
"Plug 'vim-syntastic/syntastic'
Plug 'w0rp/ale'
Plug 'Valloric/YouCompleteMe'

""" THEMES  "
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tomasr/molokai'
Plug 'morhetz/gruvbox'
Plug 'joshdick/onedark.vim'
Plug 'nanotech/jellybeans.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'ajh17/Spacegray.vim'

" Initialize plugin system
call plug#end()
